// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QuhKcnFd4932ONUjoPA3fH8C8dv3f0s',
    appId: '1:995707878804:web:7016d1e0c4a756f63c2381',
    messagingSenderId: '995707878804',
    projectId: 'map-project-df6fd',
    authDomain: 'map-project-df6fd.firebaseapp.com',
    storageBucket: 'map-project-df6fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4RAxdB7UREYpGHfHoE--rEXGtf3WTmYE',
    appId: '1:995707878804:android:e0b0e9c28bbe57ff3c2381',
    messagingSenderId: '995707878804',
    projectId: 'map-project-df6fd',
    storageBucket: 'map-project-df6fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAveSBOGODxZdh9MjhM5psAnNFE6Nbl3KI',
    appId: '1:995707878804:ios:90ffef521ab8ddfa3c2381',
    messagingSenderId: '995707878804',
    projectId: 'map-project-df6fd',
    storageBucket: 'map-project-df6fd.firebasestorage.app',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAveSBOGODxZdh9MjhM5psAnNFE6Nbl3KI',
    appId: '1:995707878804:ios:90ffef521ab8ddfa3c2381',
    messagingSenderId: '995707878804',
    projectId: 'map-project-df6fd',
    storageBucket: 'map-project-df6fd.firebasestorage.app',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4QuhKcnFd4932ONUjoPA3fH8C8dv3f0s',
    appId: '1:995707878804:web:bd37617c79e821863c2381',
    messagingSenderId: '995707878804',
    projectId: 'map-project-df6fd',
    authDomain: 'map-project-df6fd.firebaseapp.com',
    storageBucket: 'map-project-df6fd.firebasestorage.app',
  );
}
