import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class Register extends StatefulWidget {
  @override
  _RegisterState createState() => _RegisterState();
}

class _RegisterState extends State<Register> {
  // These controllers are used to capture the text the user types into the registration form fields.
  final usernameController = TextEditingController();
  final emailController = TextEditingController();
  final passwordController = TextEditingController();
  final confirmController = TextEditingController();

  // The isLoading variable tracks whether the app is currently talking to the server to register the user.
  bool isLoading = false;
  // These boolean variables keep track of the visibility states for the password and the confirm password fields respectively.
  bool obscure1 = true;
  bool obscure2 = true;

  // This asynchronous function contains the entire logic for creating a new user account.
  // It handles everything from validating the input fields to creating the authentication credential and saving extra user data in the database.
  Future<void> register() async {
    // Before talking to the server we must make sure the user did not leave any empty fields on the form.
    if (emailController.text.isEmpty ||
        passwordController.text.isEmpty ||
        confirmController.text.isEmpty ||
        usernameController.text.isEmpty) {
      await showMessage("Please fill all fields");
      return;
    }

    // We also need to verify that the password they typed matches the confirm password field to prevent typos.
    if (passwordController.text != confirmController.text) {
      await showMessage("Passwords do not match");
      return;
    }

    // Everything looks good locally so we set the loading state to true and show the loading spinner on the button.
    setState(() => isLoading = true);

    try {
      // Step one is asking Firebase Authentication to create a new user profile using the provided email and password.
      UserCredential userCredential =
      await FirebaseAuth.instance.createUserWithEmailAndPassword(
        email: emailController.text.trim(),
        password: passwordController.text.trim(),
      );

      final user = userCredential.user;

      // Step two is saving additional information about the user that authentication does not handle automatically.
      // We take the unique user ID generated by Firebase Auth and use it as the document ID in our Firestore users collection.
      // We initialize their wallet balance and count metrics to zero here.
      await FirebaseFirestore.instance
          .collection('users')
          .doc(user!.uid)
          .set({
        'username': usernameController.text,
        'email': user.email,
        'helperCount': 0,
        'requestCount': 0,
        'wallet': 0,
        'createdAt': Timestamp.now(),
      });

      // Step three is letting the user know everything worked perfectly. We show a success dialog.
      await showMessage("Register Success");

      // Once they dismiss the success dialog we automatically navigate them back to the login screen.
      Navigator.pop(context);

    } on FirebaseAuthException catch (e) {
      // If Firebase Authentication rejects the registration it throws an error.
      // We intercept the specific error code here to provide a clear and easy to understand message to the user.
      String errorMessage;

      switch (e.code) {
        case 'email-already-in-use':
          errorMessage = "Email already in use";
          break;
        case 'invalid-email':
          errorMessage = "Invalid email";
          break;
        case 'weak-password':
          errorMessage = "Password must be at least 6 characters";
          break;
        default:
          errorMessage = e.message ?? "Register Failed";
      }

      await showMessage(errorMessage);

    } catch (e) {
      // This catches any other types of errors that might occur during the database saving process or elsewhere.
      await showMessage("Something went wrong");
    }

    // Finally we always remember to turn off the loading indicator regardless of success or failure.
    setState(() => isLoading = false);
  }

  // This is a simple helper function that takes a string message and displays it inside a pop up alert dialog.
  Future<void> showMessage(String message) {
    return showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text("Message"),
        content: Text(message),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text("OK"),
          ),
        ],
      ),
    );
  }

  // This function generates the visual styling for all our input fields so we do not have to write the same design code multiple times.
  // It allows passing a hint text an icon and optionally a suffix widget like an eye button.
  InputDecoration inputStyle(String hint, IconData icon, {Widget? suffix}) {
    return InputDecoration(
      prefixIcon: Icon(icon, color: Colors.grey),
      suffixIcon: suffix,
      hintText: hint,
      hintStyle: TextStyle(color: Colors.grey),
      filled: true,
      fillColor: Colors.grey[900],
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide.none,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    // The Scaffold provides the fundamental structure for our visual interface.
    return Scaffold(
      body: Container(
        // We use the same dark gradient background as the login page for consistency across the application.
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFF0F172A), Color(0xFF020617)],
          ),
        ),
        child: SafeArea(
          // SafeArea keeps our content away from system UI elements like the top notch.
          child: Center(
            child: SingleChildScrollView(
              // We wrap everything in a Column so we can place the icon and text outside and above the main registration card.
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [

                  // This is the application icon. It is positioned in the upper center part of the screen.
                  // We increased the width and height so it looks clear and prominent even on lower resolution screens.
                  Image.asset(
                    'assets/images/CampusBugHunter_icon.png',
                    width: 90,
                    height: 90,
                  ),

                  SizedBox(height: 16),

                  // This is the welcome greeting text specifically for new registering users.
                  // The text size is reduced to fit on a single line and colored in a grayish white to serve as a subtitle.
                  Text(
                    "Welcome to Campus BugHunter!",
                    style: TextStyle(
                      fontSize: 15,
                      color: Colors.white70,
                      fontWeight: FontWeight.w500,
                    ),
                  ),

                  SizedBox(height: 35),

                  // This container holds the actual registration form fields inside a dark semi-transparent card.
                  Container(
                    width: 350,
                    padding: EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.6),
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: Column(
                      children: [

                        // This section creates a back arrow button positioned on the left side.
                        // It allows the user to easily return to the previous login screen if they change their mind.
                        Align(
                          alignment: Alignment.centerLeft,
                          child: IconButton(
                            icon: Icon(Icons.arrow_back, color: Colors.white),
                            onPressed: () => Navigator.pop(context),
                          ),
                        ),

                        // We added a small spacing between the back button and the main title to keep the layout clean.
                        SizedBox(height: 10),

                        // This is the main title text confirming the user is on the screen to create a new account.
                        Align(
                          alignment: Alignment.centerLeft,
                          child: Text(
                            "Create Account",
                            style: TextStyle(
                              fontSize: 28,
                              color: Colors.white,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),

                        SizedBox(height: 25),

                        // This is the text field where the user inputs their desired username.
                        TextField(
                          controller: usernameController,
                          style: TextStyle(color: Colors.white),
                          decoration: inputStyle("Username", Icons.person),
                        ),

                        SizedBox(height: 15),

                        // This is the text field where the user types the email address they want to register with.
                        TextField(
                          controller: emailController,
                          style: TextStyle(color: Colors.white),
                          decoration: inputStyle("Email", Icons.email),
                        ),

                        SizedBox(height: 15),

                        // This input field is for the primary password. It includes a toggle button on the right to reveal or hide the characters.
                        TextField(
                          controller: passwordController,
                          obscureText: obscure1,
                          style: TextStyle(color: Colors.white),
                          decoration: inputStyle(
                            "Password",
                            Icons.lock,
                            suffix: IconButton(
                              icon: Icon(
                                obscure1
                                    ? Icons.visibility
                                    : Icons.visibility_off,
                                color: Colors.grey,
                              ),
                              onPressed: () {
                                setState(() => obscure1 = !obscure1);
                              },
                            ),
                          ),
                        ),

                        SizedBox(height: 15),

                        // This text field requires the user to type their password a second time for confirmation. It also has a visibility toggle.
                        TextField(
                          controller: confirmController,
                          obscureText: obscure2,
                          style: TextStyle(color: Colors.white),
                          decoration: inputStyle(
                            "Confirm Password",
                            Icons.security,
                            suffix: IconButton(
                              icon: Icon(
                                obscure2
                                    ? Icons.visibility
                                    : Icons.visibility_off,
                                color: Colors.grey,
                              ),
                              onPressed: () {
                                setState(() => obscure2 = !obscure2);
                              },
                            ),
                          ),
                        ),

                        SizedBox(height: 25),

                        // The submit button fills the width of the container. It disables itself and shows a circular progress indicator when the app is processing the registration.
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton(
                            onPressed: isLoading ? null : register,
                            style: ElevatedButton.styleFrom(
                              padding: EdgeInsets.symmetric(vertical: 16),
                              backgroundColor: Colors.blue,
                            ),
                            child: isLoading
                                ? CircularProgressIndicator(color: Colors.white)
                                : Text(
                              "SUBMIT",
                              style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}